name: Build LaTeX PDF

on:
  push:
    paths:
      - "**.tex"
  pull_request:

permissions:
  contents: write

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install TeX Live (pdflatex)
        run: |
          sudo apt update
          sudo apt install -y texlive-latex-base texlive-latex-recommended texlive-latex-extra

      - name: Install latexml
        run: |
          sudo apt install -y latexml

      - name: Compile LaTeX document
        run: |
          pdflatex -interaction=nonstopmode article.tex
      
      - name: Compile xml document
        run: |
          #latexml --dest=doc.xml article
          #latexmlpost doc --dest=docs/index.html --linelength=20 --splitat=subsection
          latexml --dest=doc.xml article
          latexmlpost doc --dest=docs/index.html --linelength=20 --splitat=section --css=src/custom_css.css --javascript=src/custom_js.js --navigationtoc=context



      - name: Commit xml
        run: |
          git config --global user.name 'Pages Pusher'
          git config --global user.email 'your-username@users.noreply.github.com'
          git add docs/*
          git commit -m "Automated report"
          git push
